import { useLanguage } from "../context/LanguageContext";
import { gold } from "../utils/format";

const copy = {
  fr: {
    title: "Politique de confidentialité", updated: "Dernière mise à jour : 3 août 2026",
    intro: "Chez KinkoLab Inc., nous prenons la protection de vos renseignements personnels très au sérieux. Cette politique explique comment nous recueillons, utilisons et protégeons vos données conformément à la Loi 25 (Québec) et à la LPRPDE (Canada).",
    sections: [
      ["1. Renseignements collectés", ["Identité et contact : nom, prénom, courriel, adresses de livraison et de facturation et téléphone.", "Données de paiement des achats : elles sont traitées de façon sécurisée par Shopify et ses fournisseurs. KinkoLab ne conserve jamais vos numéros de carte.", "Renseignements de versement : nom légal, qualité du bénéficiaire, courriel Wise, consentement, campagne, montant, statut, références et preuve du transfert. Les coordonnées bancaires sont fournies directement à Wise et ne sont jamais reçues ni conservées par KinkoLab ou Firebase.", "Données de navigation : adresse IP, type de navigateur et témoins de session nécessaires au fonctionnement et à l’amélioration du site."]],
      ["2. Utilisation de vos données", ["Traiter, expédier et suivre vos commandes.", "Calculer et attribuer le soutien destiné aux athlètes sélectionnés.", "Prévenir la fraude et assurer la sécurité des transactions."]],
      ["3. Partage et conservation", ["Nous ne vendons ni ne louons vos données. Elles sont partagées uniquement avec les fournisseurs nécessaires au service, notamment Shopify, Wise, Firebase, Resend et les services de livraison.", "Le nom légal, le courriel, le montant et la référence de campagne sont communiqués à Wise pour préparer et exécuter le versement. Wise traite ensuite directement les coordonnées bancaires selon ses propres obligations.", "Les coordonnées et références qui constituent des pièces financières sont conservées jusqu’au 31 décembre de la sixième année suivant l’année financière concernée, sauf délai légal plus long, litige ou autorisation de destruction anticipée. Une tâche automatisée retire ensuite le nom légal et le courriel de versement des profils et dossiers arrivés à échéance. Les preuves minimales de consentement ou de désabonnement peuvent être conservées sans servir à la diffusion.", "Les adresses d’une liste facultative sont retirées immédiatement lors du désabonnement. Les données transactionnelles sont détruites ou rendues non identifiantes lorsque leur finalité est accomplie et qu’aucune loi n’en exige plus la conservation.", "Avant toute communication hors Québec, KinkoLab évalue les facteurs relatifs à la vie privée, notamment la sensibilité, la finalité, les mesures de protection, le lieu de traitement et le cadre contractuel applicable."]],
      ["4. Communications liées au Programme Athlètes", ["Lorsque vous déposez une candidature, effectuez une commande ou participez à une campagne, KinkoLab envoie les communications indispensables à l’exécution du service : candidature et accès au compte, commande, expédition, annulation ou remboursement, changements importants, fermeture, suivi financier, lien Wise et versement des fonds. Ces messages transactionnels et de sécurité ne sont pas des abonnements facultatifs; ils continuent même après un désabonnement promotionnel lorsqu’ils sont nécessaires à l’exécution d’une transaction, à la protection du compte ou au respect d’une obligation légale.", "Les nouvelles concernant les prochaines campagnes, les nouvelles campagnes ouvertes, les activités ou les produits KinkoLab sont envoyées uniquement aux personnes ayant coché séparément le consentement facultatif. Une case non cochée n’ajoute jamais la personne à la liste de diffusion.", "Chaque communication facultative identifie KinkoLab et comprend un lien de désabonnement simple ainsi que les en-têtes de désabonnement applicables. Le retrait est appliqué automatiquement et immédiatement à la liste KinkoLab; il ne supprime pas le courriel des dossiers transactionnels qui doivent encore être exécutés ou conservés légalement.", "Nous conservons une preuve du consentement ou du retrait, notamment sa portée, sa date, sa source et la version du texte, uniquement pour démontrer et respecter vos choix et nos obligations."]],
      ["5. Mineurs", ["Pour tout participant de moins de 18 ans, le compte du portail est créé au nom et au courriel du parent ou tuteur légal qui confirme son autorité et donne les consentements requis. Le parent ou tuteur légal est obligatoirement le bénéficiaire du versement Wise et fournit directement à Wise les coordonnées du compte bancaire dont il est titulaire.", "KinkoLab ne permet pas à un mineur de remplacer ce bénéficiaire par son propre nom ou courriel. Les règles particulières de consentement applicables aux moins de 14 ans demeurent pleinement respectées."]],
      ["6. Vos droits", ["Vous pouvez demander l’accès, la rectification ou la suppression de vos renseignements personnels, ou retirer un consentement facultatif lorsque la loi le permet. Une demande de retrait ne peut toutefois empêcher KinkoLab d’exécuter un versement dû, d’envoyer un avis transactionnel indispensable ou de conserver une pièce exigée par la loi."]],
    ],
    officer: "Responsable de la protection des renseignements personnels", contact: "Pour toute question ou demande relative à vos données, écrivez à :",
  },
  en: {
    title: "Privacy Policy", updated: "Last updated: August 3, 2026",
    intro: "At KinkoLab Inc., we take the protection of your personal information seriously. This policy explains how we collect, use and protect your data in accordance with Quebec’s Law 25 and Canada’s PIPEDA.",
    sections: [
      ["1. Information we collect", ["Identity and contact information: name, email, shipping and billing addresses, and phone number.", "Purchase payment information is securely processed by Shopify and its providers. KinkoLab never stores your card numbers.", "Payout information: legal name, beneficiary capacity, Wise email, consent, campaign, amount, status, transfer references and payment evidence. Bank details are provided directly to Wise and are never received or stored by KinkoLab or Firebase.", "Browsing data: IP address, browser type and session cookies required to operate and improve the website."]],
      ["2. How we use your information", ["Process, ship and track your orders.", "Calculate and allocate support for selected athletes.", "Prevent fraud and keep transactions secure."]],
      ["3. Sharing and retention", ["We do not sell or rent your data. It is shared only with service providers required to deliver the service, including Shopify, Wise, Firebase, Resend and shipping providers.", "Legal name, email, amount and campaign reference are communicated to Wise to prepare and execute the payout. Wise then processes bank details directly under its own obligations.", "Contact details and references that form part of financial records are retained until December 31 of the sixth year following the relevant financial year, unless a longer legal period, dispute or authorized early destruction applies. An automated task then removes legal names and payout email addresses from expired profiles and records. Minimum consent or suppression evidence may be retained without being used for mailing.", "Addresses are removed from optional mailing lists immediately upon unsubscribe. Transactional data is destroyed or rendered non-identifying once its purpose has been fulfilled and no law requires further retention.", "Before information is communicated outside Quebec, KinkoLab assesses privacy factors including sensitivity, purpose, safeguards, processing location and the applicable contractual framework."]],
      ["4. Athlete Program communications", ["When you submit an application, place an order or participate in a campaign, KinkoLab sends messages essential to providing the service: application and account access, order, shipping, cancellation or refund, significant changes, closure, financial follow-up, Wise link and payout. These transactional and security messages are not optional subscriptions and continue after promotional unsubscribe when required to complete a transaction, protect an account or comply with law.", "News about upcoming or newly opened campaigns, KinkoLab activities or products is sent only to people who separately checked the optional consent box. Leaving it unchecked never adds the person to a mailing list.", "Every optional communication identifies KinkoLab and includes a simple unsubscribe link and applicable unsubscribe headers. Withdrawal is applied automatically and immediately to KinkoLab’s mailing list; it does not erase an email from transactional records that must still be performed or legally retained.", "We retain evidence of consent or withdrawal, including scope, date, source and wording version, only to demonstrate and respect your choices and our obligations."]],
      ["5. Minors", ["For every participant under 18, the portal account is created in the name and email of the parent or legal guardian who confirms their authority and provides required consents. That parent or guardian must be the Wise payout beneficiary and provides Wise directly with banking details for an account they hold.", "KinkoLab does not allow a minor to replace that beneficiary with the minor’s own name or email. The specific consent rules applicable to children under 14 continue to apply."]],
      ["6. Your rights", ["You may request access to, correction or deletion of your personal information, or withdraw optional consent where permitted by law. A withdrawal request cannot prevent KinkoLab from completing a payment owed, sending an essential transactional notice or retaining a record required by law."]],
    ],
    officer: "Privacy Officer", contact: "For questions or requests about your personal information, email:",
  },
};

export default function PrivacyPolicyPage() {
  const { language } = useLanguage();
  const page = copy[language];
  return <main className="min-h-screen bg-black px-5 py-16 text-white"><article className="mx-auto max-w-4xl rounded-[2rem] border border-zinc-800 bg-zinc-950 p-6 shadow-2xl md:p-10">
    <h1 className="text-4xl font-black md:text-5xl">{page.title}</h1><p className="mt-3 text-zinc-400">{page.updated}</p>
    <p className="mt-8 leading-8 text-zinc-300">{page.intro}</p>
    {page.sections.map(([title, items]) => <section key={title}><h2 className="mt-10 text-2xl font-black" style={{ color: gold }}>{title}</h2><ul className="mt-4 list-disc space-y-3 pl-6 text-zinc-300">{items.map((item) => <li key={item}>{item}</li>)}</ul></section>)}
    <section className="mt-10 rounded-2xl border border-zinc-700 bg-black p-6"><h2 className="text-xl font-black">{page.officer}</h2><p className="mt-3 text-zinc-300">{page.contact} <a className="font-bold underline" style={{ color: gold }} href="mailto:privacy@kinkolab.com">privacy@kinkolab.com</a></p></section>
  </article></main>;
}
