import { useLanguage } from "../context/LanguageContext";
import { gold } from "../utils/format";

const copy = {
  fr: {
    title: "Transparence financière",
    subtitle: "Comment fonctionne la répartition financière du Programme Athlètes KinkoLab",
    intro:
      "Chez KinkoLab Inc., nous croyons qu’un programme de soutien responsable doit présenter des règles simples, claires et accessibles. Voici comment les revenus générés par les produits supporters sont répartis et versés.",
    exampleTitle: "Exemple de répartition pour une vente de 60 $",
    athleteAmount: "20,00 $",
    athleteLabel: "Attribués à l’athlète",
    athleteDescription: "Montant fixe par article vendu, avant taxes et sous réserve de validation.",
    kinkoAmount: "40,00 $",
    kinkoLabel: "Part KinkoLab Inc.",
    kinkoDescription: "Production, matières, logistique, paiement sécurisé et administration.",
    notice:
      "L’achat d’un produit supporter est une transaction commerciale et non un don de bienfaisance. Aucun reçu fiscal n’est émis.",
    processTitle: "Mécanisme de versement aux athlètes",
    processIntro:
      "Les sommes associées aux ventes ne transitent pas par une cagnotte publique. Elles sont suivies dans le cadre d’un processus administratif contrôlé.",
    steps: [
      {
        number: "01",
        title: "Validation de la vente",
        text: "Une vente est confirmée après un délai de 14 jours afin de tenir compte des fraudes potentielles, annulations, remboursements et problèmes de produit.",
      },
      {
        number: "02",
        title: "Suivi des montants",
        text: "La contribution associée à chaque vente validée est ajoutée au suivi financier de l’athlète ou de la famille concernée.",
      },
      {
        number: "03",
        title: "Versement périodique",
        text: "KinkoLab verse les sommes accumulées selon la fréquence et les modalités prévues dans l’entente conclue avec l’athlète ou sa famille.",
      },
      {
        number: "04",
        title: "Bénéficiaire légal",
        text: "Le versement est effectué à l’athlète majeur ou au parent ou tuteur légal lorsque l’athlète est mineur.",
      },
    ],
    adjustmentsTitle: "Ajustements possibles",
    adjustments:
      "Les montants affichés peuvent être corrigés lorsqu’une commande est annulée ou remboursée, qu’un paiement est contesté ou qu’une erreur administrative est constatée.",
    contactTitle: "Une question sur le programme ?",
    contactText: "Pour toute question concernant un bilan de campagne ou le fonctionnement financier, écrivez-nous à",
  },
  en: {
    title: "Financial transparency",
    subtitle: "How funds are allocated within the KinkoLab Athlete Program",
    intro:
      "At KinkoLab Inc., we believe a responsible support program should have simple, clear and accessible rules. Here is how revenue generated by supporter products is allocated and paid out.",
    exampleTitle: "Sample allocation for a $60 sale",
    athleteAmount: "$20.00",
    athleteLabel: "Allocated to the athlete",
    athleteDescription: "Fixed amount per item sold, before taxes and subject to validation.",
    kinkoAmount: "$40.00",
    kinkoLabel: "KinkoLab Inc. share",
    kinkoDescription: "Production, materials, logistics, secure payment processing and administration.",
    notice:
      "Purchasing a supporter product is a commercial transaction, not a charitable donation. No tax receipt is issued.",
    processTitle: "How athletes receive their funds",
    processIntro:
      "Funds associated with sales do not pass through a public donation pool. They are tracked through a controlled administrative process.",
    steps: [
      {
        number: "01",
        title: "Sale validation",
        text: "A sale is confirmed after 14 days to account for potential fraud, cancellations, refunds and product issues.",
      },
      {
        number: "02",
        title: "Fund tracking",
        text: "The contribution associated with each validated sale is added to the financial record of the relevant athlete or family.",
      },
      {
        number: "03",
        title: "Periodic payment",
        text: "KinkoLab pays accumulated funds according to the schedule and terms set out in the agreement with the athlete or their family.",
      },
      {
        number: "04",
        title: "Legal beneficiary",
        text: "Payment is made to an adult athlete or to the parent or legal guardian when the athlete is a minor.",
      },
    ],
    adjustmentsTitle: "Possible adjustments",
    adjustments:
      "Displayed amounts may be corrected if an order is cancelled or refunded, a payment is disputed, or an administrative error is identified.",
    contactTitle: "Have a question about the program?",
    contactText: "For questions about campaign statements or how the financial process works, email us at",
  },
};

export default function TransparencyPage() {
  const { language } = useLanguage();
  const page = copy[language] || copy.fr;

  return (
    <main className="min-h-screen bg-black px-5 py-16 text-white">
      <article className="mx-auto max-w-4xl rounded-[2rem] border border-zinc-800 bg-zinc-950 p-6 shadow-2xl md:p-10">
        <header>
          <h1 className="text-4xl font-black md:text-5xl">{page.title}</h1>
          <p className="mt-3 text-lg leading-7 text-zinc-400">{page.subtitle}</p>
        </header>

        <p className="mt-8 text-lg leading-8 text-zinc-300">{page.intro}</p>

        <section className="mt-10">
          <h2 className="text-2xl font-black" style={{ color: gold }}>
            {page.exampleTitle}
          </h2>

          <div className="mt-6 grid gap-4 md:grid-cols-2">
            <div className="rounded-2xl border border-yellow-700/50 bg-yellow-950/20 p-6">
              <p className="text-4xl font-black" style={{ color: gold }}>
                {page.athleteAmount}
              </p>
              <h3 className="mt-3 text-lg font-black text-white">{page.athleteLabel}</h3>
              <p className="mt-2 leading-7 text-zinc-300">{page.athleteDescription}</p>
            </div>

            <div className="rounded-2xl border border-zinc-700 bg-black p-6">
              <p className="text-4xl font-black text-white">{page.kinkoAmount}</p>
              <h3 className="mt-3 text-lg font-black text-white">{page.kinkoLabel}</h3>
              <p className="mt-2 leading-7 text-zinc-300">{page.kinkoDescription}</p>
            </div>
          </div>

          <div className="mt-4 rounded-2xl border border-yellow-700/40 bg-yellow-950/20 p-5">
            <p className="leading-7 text-yellow-100">
              <strong>{language === "en" ? "Important:" : "Important :"}</strong>{" "}
              {page.notice}
            </p>
          </div>
        </section>

        <section className="mt-12">
          <h2 className="text-2xl font-black" style={{ color: gold }}>
            {page.processTitle}
          </h2>
          <p className="mt-4 leading-8 text-zinc-300">{page.processIntro}</p>

          <div className="mt-6 grid gap-4 md:grid-cols-2">
            {page.steps.map((step) => (
              <div key={step.number} className="rounded-2xl border border-zinc-800 bg-black p-6">
                <p className="text-sm font-black tracking-[0.2em]" style={{ color: gold }}>
                  {step.number}
                </p>
                <h3 className="mt-3 text-xl font-black text-white">{step.title}</h3>
                <p className="mt-3 leading-7 text-zinc-300">{step.text}</p>
              </div>
            ))}
          </div>
        </section>

        <section className="mt-10 rounded-2xl border border-zinc-700 bg-black p-6">
          <h2 className="text-xl font-black text-white">{page.adjustmentsTitle}</h2>
          <p className="mt-3 leading-7 text-zinc-300">{page.adjustments}</p>
        </section>

        <section className="mt-10 border-t border-zinc-800 pt-8">
          <h2 className="text-xl font-black text-white">{page.contactTitle}</h2>
          <p className="mt-3 leading-7 text-zinc-300">
            {page.contactText}{" "}
            <a
              className="font-bold underline underline-offset-4"
              style={{ color: gold }}
              href="mailto:athletes@kinkolab.com"
            >
              athletes@kinkolab.com
            </a>
            .
          </p>
        </section>
      </article>
    </main>
  );
}
